#!/usr/bin/env python3
"""Write experiments/RESULTS.md from the recorded comparisons.

The report and the dashboard must use the same evidence, so the report's tables
are generated from experiments/comparisons/*.json - never typed by hand. Every
row names the run it came from.

    .venv/bin/python scripts/report_tables.py
"""
from __future__ import annotations

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from echo_sim import evidence as EV  # noqa: E402
from echo_sim import scenarios as S  # noqa: E402

LABEL = {"tcp_reconnect": "TCP reconnect", "quic_fixed": "QUIC fixed server",
         "measured": "Measurement-driven", "predictive": "Predictive"}
ROWS = [
    ("late150", "Late results (>150 ms or lost)", "%"),
    ("late100", "Late results (>100 ms or lost)", "%"),
    ("late200", "Late results (>200 ms or lost)", "%"),
    ("p95_ms", "p95 response time", "ms"),
    ("median_ms", "Median response time", "ms"),
    ("results_lost", "Lost results", ""),
    ("longest_gap_ms", "Longest result gap", "ms"),
    ("completed_handovers", "Completed handovers", ""),
    ("failed_handovers", "Failed handovers", ""),
    ("reconnects", "Reconnects (session rebuilt)", ""),
    ("unnecessary_reversals", "Unnecessary reversals", ""),
    ("time_on_suboptimal_server_s", "Time on a server that was not the best", "s"),
    ("continuity_checks_passed", "Continuity checks passed", ""),
    ("continuity_checks_failed", "Continuity checks failed", ""),
    ("playback_stalls", "Playback stalls", ""),
    ("playback_stall_time_s", "Time stalled", "s"),
    ("min_buffer_s", "Lowest buffer while playing", "s"),
]


def value(metrics, key):
    if key.startswith("late"):
        v = (metrics.get("late_by_threshold") or {}).get(key[4:], {}).get("pct")
    else:
        v = metrics.get(key)
    return v


def fmt(v, unit):
    if v is None:
        return "-"
    if isinstance(v, float):
        v = f"{v:.1f}" if unit in ("%", "s") else f"{v:.0f}"
    return f"{v} {unit}".strip()


def main() -> None:
    comps = EV.list_comparisons()
    # newest comparison per (scenario, profile, origin set)
    seen, chosen = set(), []
    for c in comps:
        origins = tuple(sorted({m["data_origin"] for m in c["modes"].values()}))
        key = (c["scenario_id"], c["application_profile"], origins)
        if key not in seen:
            seen.add(key)
            chosen.append(c)
    order = list(S.SCENARIOS)
    chosen.sort(key=lambda c: (order.index(c["scenario_id"]) if c["scenario_id"] in order else 99,
                               c["application_profile"] != "interactive_inspection",
                               c["scenario_version"] or 0))
    out = ["# ECHO results (generated)", "",
           "Generated by `scripts/report_tables.py` from `experiments/comparisons/`. "
           "Do not edit by hand; re-run the script. Every column is one run, named "
           "under its table; download it from the dashboard or read "
           "`experiments/runs/<run-id>/`.", "",
           "Single seed per controller: these are single runs, not distributions.", ""]
    for c in chosen:
        playback = c["application_profile"] == "buffered_playback"
        scen = S.SCENARIOS.get(c["scenario_id"])
        title = scen.title if scen and c["scenario_version"] == scen.version else \
            f"{c['scenario_id']} v{c['scenario_version']}"
        origins = sorted({m["data_origin"] for m in c["modes"].values()})
        out += [f"## {title} - {c['application_profile']}", "",
                f"Comparison `{c['comparison_id']}` · scenario version "
                f"{c['scenario_version']} · seed {c['seed']} · origin {', '.join(origins)}"
                + (f" · {c['note']}" if c.get("note") else ""), ""]
        modes = list(c["modes"])
        out.append("| Measure | " + " | ".join(LABEL.get(m, m) for m in modes) + " |")
        out.append("|---|" + "---:|" * len(modes))
        for key, name, unit in ROWS:
            if not playback and key in ("playback_stalls", "playback_stall_time_s",
                                        "min_buffer_s"):
                continue
            if playback and key.startswith("late"):
                continue   # segments are fetched ahead; the deadline does not apply
            vals = [value(c["modes"][m]["metrics"], key) for m in modes]
            if all(v is None for v in vals):
                continue
            out.append(f"| {name} | " + " | ".join(fmt(v, unit) for v in vals) + " |")
        out.append("")
        out.append("Runs: " + " · ".join(
            f"{LABEL.get(m, m)} `{c['modes'][m]['run_id']}`" for m in modes))
        out.append("")
    path = os.path.join(EV.EXPERIMENTS, "RESULTS.md")
    with open(path, "w") as fh:
        fh.write("\n".join(out))
    print(f"wrote {path}")


if __name__ == "__main__":
    main()
